CREATE TABLE jdbc_customer ( customer_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(50), email VARCHAR(50) NOT NULL UNIQUE, birth_date DATE, gender VARCHAR(50) );
CREATE TABLE jdbc_merchant ( merchant_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, merchant_name VARCHAR(50), email VARCHAR(50), description text );
CREATE TABLE jpa_customer ( customer_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(50), email VARCHAR(50) NOT NULL UNIQUE, birth_date DATE, gender VARCHAR(50) );
CREATE TABLE xss_article ( article_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, article text NOT NULL );
CREATE TABLE basic_auth_user ( user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, username VARCHAR(150) NOT NULL UNIQUE, password_hash VARCHAR(100) NOT NULL, salt VARCHAR(16) NOT NULL UNIQUE, display_name VARCHAR(50) );
CREATE TABLE basic_acl_uri ( uri_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, METHOD VARCHAR(100) NOT NULL, uri VARCHAR(300) NOT NULL );
CREATE TABLE basic_acl_user_uri_ref ( user_id INTEGER, uri_id INTEGER );
CREATE TABLE basic_apikey(apikey_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, user_id INT, apikey VARCHAR(64) NOT NULL UNIQUE, expired_at TIMESTAMP WITHOUT TIME zone);